---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Materiais para estudar R

O conteúdo desse repositório foi movido para [esse site](https://materiais-estudo-r.netlify.app/). 

Para enviar contribuições, faça uma contribuição [neste arquivo](https://github.com/beatrizmilz/materiais_estudo_R/blob/master/inst/dados.csv), ou [escreva uma issue](https://github.com/beatrizmilz/materiais_estudo_R/issues/new/choose).


```{r message=FALSE, warning=FALSE, include=FALSE}
library(magrittr, include.only = "%>%")
data_raw <- readr::read_csv("inst/dados.csv")
quem_contribui <- readr::read_csv2("inst/lista_de_pessoas_contribuidoras.csv")
```

## Quem contribui?

```{r echo=FALSE, results='asis'}
quem_contribui %>% 
  dplyr::mutate(link = glue::glue("[{logins}]({url})")) %>% 
  dplyr::filter(logins !=  "actions-user") %>% 
  dplyr::select(link) %>% 
  dplyr::summarise(texto = knitr::combine_words(link, and = " e ")) %>% 
  dplyr::pull(texto)
```

## Materiais

```{r echo=FALSE}
data <- data_raw %>% 
  tidyr::drop_na(url) %>% 
 dplyr::arrange(categoria) %>% 
  dplyr::mutate(material = glue::glue("[{titulo}]({url})"))  %>%
  dplyr::select(material, autoria, categoria, tema)
    
    
knitr::kable(data)
```

